/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAiRewriteRouteImport } from './routes/api/public/ai-rewrite'
import { Route as ApiPublicAiRouterRouteImport } from './routes/api/public/ai-router'
import { Route as ApiPublicOpenrouterRouteImport } from './routes/api/public/openrouter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiRewriteRoute = ApiPublicAiRewriteRouteImport.update({
  id: '/api/public/ai-rewrite',
  path: '/api/public/ai-rewrite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiRouterRoute = ApiPublicAiRouterRouteImport.update({
  id: '/api/public/ai-router',
  path: '/api/public/ai-router',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenrouterRoute = ApiPublicOpenrouterRouteImport.update({
  id: '/api/public/openrouter',
  path: '/api/public/openrouter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/ai-rewrite': typeof ApiPublicAiRewriteRoute
  '/api/public/ai-router': typeof ApiPublicAiRouterRoute
  '/api/public/openrouter': typeof ApiPublicOpenrouterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/ai-rewrite': typeof ApiPublicAiRewriteRoute
  '/api/public/ai-router': typeof ApiPublicAiRouterRoute
  '/api/public/openrouter': typeof ApiPublicOpenrouterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/ai-rewrite': typeof ApiPublicAiRewriteRoute
  '/api/public/ai-router': typeof ApiPublicAiRouterRoute
  '/api/public/openrouter': typeof ApiPublicOpenrouterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/ai-rewrite'
    | '/api/public/ai-router'
    | '/api/public/openrouter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/ai-rewrite'
    | '/api/public/ai-router'
    | '/api/public/openrouter'
  id:
    | '__root__'
    | '/'
    | '/api/public/ai-rewrite'
    | '/api/public/ai-router'
    | '/api/public/openrouter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAiRewriteRoute: typeof ApiPublicAiRewriteRoute
  ApiPublicAiRouterRoute: typeof ApiPublicAiRouterRoute
  ApiPublicOpenrouterRoute: typeof ApiPublicOpenrouterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-rewrite': {
      id: '/api/public/ai-rewrite'
      path: '/api/public/ai-rewrite'
      fullPath: '/api/public/ai-rewrite'
      preLoaderRoute: typeof ApiPublicAiRewriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-router': {
      id: '/api/public/ai-router'
      path: '/api/public/ai-router'
      fullPath: '/api/public/ai-router'
      preLoaderRoute: typeof ApiPublicAiRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openrouter': {
      id: '/api/public/openrouter'
      path: '/api/public/openrouter'
      fullPath: '/api/public/openrouter'
      preLoaderRoute: typeof ApiPublicOpenrouterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAiRewriteRoute: ApiPublicAiRewriteRoute,
  ApiPublicAiRouterRoute: ApiPublicAiRouterRoute,
  ApiPublicOpenrouterRoute: ApiPublicOpenrouterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
